name: Build project

on: [push, pull_request]

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # iOS, Android
        targetPlatform: [ StandaloneOSX, StandaloneWindows, StandaloneLinux64, WebGL ]
        include:
          - targetPlatform: StandaloneOSX
            deployVar: osx
          - targetPlatform: StandaloneWindows
            deployVar: windows
          - targetPlatform: StandaloneLinux64
            deployVar: linux
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
      # Upload To Itch.io
      - uses: josephbmanley/butler-publish-itchio-action@master
        if: ${{ matrix.targetPlatform != "WebGL" }}
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ matrix.deployVar }}
          ITCH_GAME: sporent
          ITCH_USER: sergioribera
          PACKAGE: build/${{ matrix.targetPlatform }}
      # Upload To Release
      # Upload to Artifact
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: Build-${{ matrix.targetPlatform }}
      #    path: build/${{ matrix.targetPlatform }}
